Repository R0Y15/WeatherNow, pull requests merged in 2023-10, with the labels that each got.

#5 #1 fixed
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added Icons to weather data and removed blank div border at rest
  index.html
  script.js
  style.css
Labels: hacktoberfest-accepted

#15 Add inline graph to show hourly forecast of input city issue #11
  index.html
  script.js
Labels: hacktoberfest-accepted

#19 contributors.html
  contributors.html
Labels: hacktoberfest-accepted

#21 feat/added a loader before the result renders
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#27 Update style.css
  style.css
Labels: hacktoberfest-accepted

#32 Hide result container on error
  script.js
Labels: hacktoberfest-accepted

#31 Made website responsive for all devices
  index.html
  script.js
  style.css
Labels: enhancement, good first issue, hacktoberfest

#35 Dynamic copyright year
  index.html
  script.js
Labels: good first issue, hacktoberfest-accepted

#38 Update
  About.html
  about-style.css
  contri-style.css
  contributors.html
  index.html
Labels: enhancement, hacktoberfest-accepted

#39 Back button positioning fixed
  contri-style.css
  contributors.html
Labels: enhancement, hacktoberfest-accepted

#43 Add Different Graph Types
  contributors.html
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#45 feat: proper folder structure for CSS and JS files
  About.html
  contributors.html
  css/about-style.css
  css/contri-style.css
  css/style.css
  index.html
  js/script.js
Labels: hacktoberfest-accepted

#46 add API Key Security
  index.html
  js/config.js
  js/script.js
Labels: hacktoberfest, hacktoberfest-accepted
