Repository R0Y15/WeatherNow, pull requests merged in 2024-10, with the labels that each got.

#50 maded the update chart function properly
  index.html
  js/script.js
Labels: hacktoberfest-accepted

#52 Integrated The Contributors Page.
  contributors.html
Labels: hacktoberfest-accepted

#55 feat: popular cities name
  index.html
Labels: hacktoberfest-accepted

#59 Enhance the readme
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#61 Changed Theme
  About.html
  css/about-style.css
  css/style.css
Labels: hacktoberfest-accepted

#67 Add Responsive Navbar and Update About Page Styling
  About.html
  css/about-style.css
  css/contri-style.css
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#66 Updated button HTML and CSS while enhancing hover effects for smoothe…
  css/style.css
  index.html
Labels: hacktoberfest-accepted

#76 fixed position of button in contributors page
  css/contri-style.css
Labels: hacktoberfest, hacktoberfest-accepted

#83 name, country and visibility feature added in graph
  js/geolocation.js
  js/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#84 Fix layout overflow issues for screens between 768px and 1000px
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#89 currloc_button Chnaged
  .vscode/settings.json
  css/style.css
Labels: hacktoberfest-accepted

#93 Update font
  css/about-style.css
  css/contri-style.css
  css/style.css
Labels: good first issue, hacktoberfest-accepted

#97 About Page UI enhanced
  About.html
  css/about-style.css
  css/check.svg
Labels: hacktoberfest, hacktoberfest-accepted

#90 feat: Sunrise sunset
  index.html
  js/geolocation.js
  js/script.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#103 Contributors page Re-Designed
  contributors.html
  css/contri-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#107 Added Sticky Navbar on contributors page
  css/contri-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktober2024

#106 Added scroll to top button on contributors page
  contributors.html
  css/contri-style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober2024

#120 Update style.css
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober2024

#121 Display of Air Quality Index (AQI) and Voice Search Functionality
  css/style.css
  index.html
  js/script.js
Labels: enhancement, good first issue

#123 Footer improvement
  About.html
  css/about-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#126 Fixes 119: About us page redesigned
  About.html
  css/about-style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober2024

#130 I am learning coding
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktober2024

#133 Add CSS Transitions and Hover Effects for Improved UI
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober2024

#132 Fixed the UI and UX of Navigation bar on issue #128
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktober2024

#134 --Added updateBackground function for currentLocation and getWeather
  js/geolocation.js
  js/script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktober2024
